/**
 * Generates src/content/resorts/data.ts from the worldwide resort seed in
 * alpline-admin/ski-platform-main.
 *
 * The backend's own resorts table carries no slug, country or region — the OSM
 * pipeline writes only a bounding box — so a directory grouped by country
 * cannot be built from the API today. This dataset supplies those fields.
 *
 * Re-run with: node scripts/build-resorts.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";

const SRC =
  "/Users/varnie/Projects/alpline/alpline-admin/ski-platform-main/supabase/migrations/20260202000002_seed_worldwide_resorts.sql";

const CONTINENTS = {
  France: "Europe", Austria: "Europe", Switzerland: "Europe", Italy: "Europe",
  Spain: "Europe", Norway: "Europe", Andorra: "Europe", Sweden: "Europe",
  Finland: "Europe", Germany: "Europe", Slovenia: "Europe", Bulgaria: "Europe",
  Romania: "Europe", Poland: "Europe", "Czech Republic": "Europe",
  Slovakia: "Europe", Georgia: "Europe", Turkey: "Europe",
  USA: "North America", Canada: "North America",
  Japan: "Asia", "South Korea": "Asia",
  "New Zealand": "Oceania", Australia: "Oceania",
  Chile: "South America", Argentina: "South America",
};

/**
 * Resorts whose piste and lift networks the production pipeline actually
 * ingests, from the --resorts allowlist in alpline-backend/terraform/
 * cloudrun.tf: the Chamonix valley and the Trois Vallees network.
 * Everything else is catalogued but not yet mapped.
 */
const LIVE = new Set([
  "chamonix",
  "val-thorens",
  "courchevel",
  "meribel",
  "les-menuires",
]);

const sql = readFileSync(SRC, "utf8");
const rows = [];

for (const line of sql.split("\n")) {
  if (!line.startsWith("  ('")) continue;
  const inner = line.trim().replace(/[,;]\s*$/, "").replace(/^\(/, "").replace(/\)$/, "");

  // Split on commas that are not inside a quoted string ('' escapes a quote).
  const fields = [];
  let buf = "";
  let quoted = false;
  for (let i = 0; i < inner.length; i++) {
    const c = inner[i];
    if (c === "'") {
      if (quoted && inner[i + 1] === "'") { buf += "'"; i++; continue; }
      quoted = !quoted;
      continue;
    }
    if (c === "," && !quoted) { fields.push(buf.trim()); buf = ""; continue; }
    buf += c;
  }
  fields.push(buf.trim());

  const [name, slug, lat, lng, min, max, country, region] = fields;
  const continent = CONTINENTS[country];
  if (!continent) throw new Error(`No continent mapped for country: ${country}`);

  rows.push({
    slug, name, country, region, continent,
    lat: Number(lat), lng: Number(lng),
    altitudeMin: Number(min), altitudeMax: Number(max),
    coverage: LIVE.has(slug) ? "live" : "catalogued",
  });
}

const slugs = new Set(rows.map((r) => r.slug));
if (slugs.size !== rows.length) throw new Error("duplicate resort slug");
for (const s of LIVE) {
  if (!slugs.has(s)) throw new Error(`LIVE slug "${s}" is not in the dataset`);
}

rows.sort((a, b) => a.name.localeCompare(b.name, "en"));

const out = `// GENERATED by scripts/build-resorts.mjs — do not edit by hand.
// Source: alpline-admin/ski-platform-main worldwide resort seed.
import type { Resort } from "./types";

export const resorts: Resort[] = ${JSON.stringify(rows, null, 2)};
`;
writeFileSync("src/content/resorts/data.ts", out);

const live = rows.filter((r) => r.coverage === "live").length;
console.log(`${rows.length} resorts, ${slugs.size} unique slugs, ${live} live`);
const byContinent = {};
for (const r of rows) byContinent[r.continent] = (byContinent[r.continent] ?? 0) + 1;
console.log(byContinent);
